version: '3.9'

services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/src
    #command: /bin/bash -c "cd fullstack-develop-example-at-django-nuxtjs && npm run dev"
    ports:
      - "3000:3000"
    tty: true
  backend:
    build:
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/src
    command: /bin/bash -c "./manage.py runserver 0.0.0.0:8000 --settings config.settings.development"
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8089:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: hogehoge@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

volumes:
  postgres_volume: 
  pgadmin4_data: